### ISSUE TITLE
Lombok not working as expected after update to 6.2.0 (Java 16, Spring 2.5.5, Gradle 7.2)

### ISSUE THREAD

**Issue by jenni** [freefair/gradle-plugins#404]
We have updated our project to Java 16, Spring Boot 2.5.5, Gradle 7.2... other dependencies, and Lombok to 6.2.0.

We have only one `lombok.config` file located in the root of the project:
```
config.stopBubbling = true
lombok.accessors.chain = true
lombok.addLombokGeneratedAnnotation = true
lombok.addSuppressWarnings = true
```

Since the update we started to get a bunch of errors that indicate Lombok is not working as expected:

examples:
```
#17 236.9 /app/src/main/java/com/collabary/common/entities/sharedaccess/contentApproval/ContentApprovalLook.java:26: error: void cannot be dereferenced
#17 236.9         return new ContentApprovalLook().setCampaignId(campaignId).setTitle(title);
#17 236.9                                                                                                                    ^
```
```
#17 238.1 /app/src/main/java/com/collabary/common/entities/campaign/deliverable/InstagramStoryMetricsAsset.java:57: error: setStickerTaps(Integer) in RecognizedAnalyticsData cannot implement setStickerTaps(Integer) in InstagramMetricsData
#17 238.1     @Setter
#17 238.1     ^
```

The version `id 'io.freefair.lombok' version '5.3.3.3'` works fine.

**Comment by larsgrefer** [comment]
Could you have a look at `build/lombok/effective-config/` please?
